image: docker-reg.devops.xiaohongshu.com/fe/fe-ci:$FE_CI_IMAGE_LATEST

before_script:
  - node -v
  - formula -V
  - npm i

stages:
  - test
  - deploy

test:
  stage: test
  script:
    # - formula lint
    - formula test


deploy:production:
  stage: deploy
  script:
    - npm publish
  only:
    - /^v\d+\.\d+\.\d+$/

deploy:prerelease:
  stage: deploy
  script:
    - npm publish --tag=prerelease
  only:
    - /^v\d+\.\d+\.\d+-\d+$/
